replicaCount: 2

service:
  port: 5000

image:
  repository: orkesio/orkes-conductor-community
  tag: 1.0.3
  pullPolicy: Always
  livenessPort: 8080


app:
  resources:
    cpuLimit: "3"
    memoryLimit: "3Gi"
    cpuRequests: "2"
    memoryRequests: "2Gi"

redis:
  host: host
  port: "6379"
  password: ""

postgres:
  username: "username"
  password: "password"
  url: "jdbc:postgresql:/host:5432/postgres"

# imageCredentials:
#   registry: https://index.docker.io/v1/
#   username: orkesdocker
#   password: <YOUR SECRET>
#   email: dockeracess@orkes.io